#!/usr/bin/env python
"""
Provides an EmbargoEvent object for the Vultron ActivityStreams Vocabulary.
"""

#  Copyright (c) 2023-2025 Carnegie Mellon University and Contributors.
#  - see Contributors.md for a full list of Contributors
#  - see ContributionInstructions.md for information on how you can Contribute to this project
#  Vultron Multiparty Coordinated Vulnerability Disclosure Protocol Prototype is
#  licensed under a MIT (SEI)-style license, please see LICENSE.md distributed
#  with this Software or contact permission@sei.cmu.edu for full terms.
#  Created, in part, with funding and support from the United States Government
#  (see Acknowledgments file). This program may include and/or can make use of
#  certain third party source code, object code, documentation and other files
#  (“Third Party Software”). See LICENSE.md for more details.
#  Carnegie Mellon®, CERT® and CERT Coordination Center® are registered in the
#  U.S. Patent and Trademark Office by Carnegie Mellon University

from datetime import datetime, timedelta
from typing import Literal, TypeAlias, cast

from pydantic import Field, model_validator

from vultron.core.models.embargo_event import EmbargoEvent as CoreEmbargoEvent
from vultron.wire.as2.vocab.base.dt_utils import (
    now_utc,
)
from vultron.wire.as2.vocab.base.links import ActivityStreamRef
from vultron.wire.as2.vocab.base.objects.object_types import as_Event
from vultron.wire.as2.vocab.base.utils import name_of
from vultron.wire.as2.vocab.objects.base import (
    _scalar_ref_id_or_value,
    _strip_core_context,
)


def _45_days_hence():
    now = now_utc()
    return now + timedelta(days=45)


class as_EmbargoEvent(as_Event):
    """Wire projection of the core EmbargoEvent domain object.

    Represents an embargo on a VulnerabilityCase for AS2 wire exchange.
    Domain logic lives in :class:`vultron.core.models.embargo_event.EmbargoEvent`.
    """

    type_: Literal["EmbargoEvent"] = Field(  # type: ignore[assignment]
        default="EmbargoEvent",
        validation_alias="type",
        serialization_alias="type",
    )

    start_time: datetime = Field(
        default_factory=now_utc, json_schema_extra={"format": "date-time"}
    )
    end_time: datetime = Field(
        default_factory=_45_days_hence,
        json_schema_extra={"format": "date-time"},
    )

    # we don't need separate validators for start_time and end_time
    # because the base class validator will be called for both fields

    @model_validator(mode="after")
    def set_name(self):
        start_iso = self.start_time.isoformat()
        end_iso = self.end_time.isoformat()

        parts = [
            "Embargo for",
            name_of(self.context),
        ]
        if self.start_time:
            parts.append(f"start: {start_iso}")
        if self.end_time:
            parts.append(f"end: {end_iso}")
        self.name = " ".join([str(part) for part in parts])
        return self

    @classmethod
    def from_core(cls, core_obj: CoreEmbargoEvent) -> "as_EmbargoEvent":
        data = core_obj.model_dump(mode="json")
        _strip_core_context(data)
        return cast("as_EmbargoEvent", cls.model_validate(data))

    def to_core(self) -> CoreEmbargoEvent:
        data = self.model_dump(mode="python", round_trip=True)
        data["context"] = _scalar_ref_id_or_value(data.get("context"))
        # Drop the wire-synthesized name — it is generated by set_name and
        # is not a property of the core domain object.
        data.pop("name", None)
        return CoreEmbargoEvent.model_validate(data)


as_EmbargoEventRef: TypeAlias = ActivityStreamRef[as_EmbargoEvent]


def main():
    obj = as_EmbargoEvent()
    print(obj.to_json(indent=2))


if __name__ == "__main__":
    main()
