/**
 * Protocol source of truth for the demos.
 *
 * This module is the ONE place in `ui/` that reads the committed protocol-state
 * artifact (`data/json/protocol_states.json`, generated by
 * `vultron/scripts/export_states.py` from `vultron.core.states`). Everything
 * else — action handlers, action filters — must go through the helpers here
 * rather than hardcoding which states/transitions the protocol allows.
 *
 * See ui/CLAUDE.md §9 for the deferral effort this supports.
 *
 * The four machines (per ui/CLAUDE.md §3):
 *   - rm  — Report Management   (per-participant)
 *   - em  — Embargo Management  (case-level)
 *   - vfd — Vendor Fix Develop. (per-participant; the vfd→Vfd→VFd→VFD ladder)
 *   - pxa — Public/eXploit/Attacks (case-level)
 */

import protocolStates from '../../data/json/protocol_states.json'

export type MachineName = 'rm' | 'em' | 'vfd' | 'pxa'

interface RawTransition {
  trigger: string
  source: string
  dest: string
}

interface RawMachine {
  initial: string
  states: string[]
  transitions: RawTransition[]
}

// The JSON carries a leading `_README` key alongside the four machines. Narrow
// to just the machines we care about; the cast is safe because the drift test
// (test/test_demo_states_export.py) guards the artifact's shape.
const MACHINES: Record<MachineName, RawMachine> = {
  rm: protocolStates.rm as RawMachine,
  em: protocolStates.em as RawMachine,
  vfd: protocolStates.vfd as RawMachine,
  pxa: protocolStates.pxa as RawMachine,
}

/**
 * Per-machine lookup: source state -> trigger -> dest state.
 * Built once at module load so `nextState`/`legalTriggers` are O(1)/O(k).
 */
const TRANSITION_INDEX: Record<MachineName, Map<string, Map<string, string>>> =
  (Object.keys(MACHINES) as MachineName[]).reduce((acc, name) => {
    const bySource = new Map<string, Map<string, string>>()
    for (const t of MACHINES[name].transitions) {
      let byTrigger = bySource.get(t.source)
      if (!byTrigger) {
        byTrigger = new Map<string, string>()
        bySource.set(t.source, byTrigger)
      }
      byTrigger.set(t.trigger, t.dest)
    }
    acc[name] = bySource
    return acc
  }, {} as Record<MachineName, Map<string, Map<string, string>>>)

/** The initial state for a machine (e.g. rm → 'START', vfd → 'vfd'). */
export function initialState(machine: MachineName): string {
  return MACHINES[machine].initial
}

/** All declared states for a machine, in artifact order. */
export function machineStates(machine: MachineName): readonly string[] {
  return MACHINES[machine].states
}

/** True if `state` is a declared state of `machine`. */
export function isValidState(machine: MachineName, state: string): boolean {
  return MACHINES[machine].states.includes(state)
}

/**
 * Apply `trigger` to `current` and return the destination state, or `null` if
 * the protocol has no such transition from `current`. Callers that expect the
 * transition to be legal should treat `null` as a bug (see `requireNextState`).
 */
export function nextState(
  machine: MachineName,
  current: string,
  trigger: string
): string | null {
  return TRANSITION_INDEX[machine].get(current)?.get(trigger) ?? null
}

/**
 * Like `nextState`, but throws if the transition is illegal. Use in action
 * handlers where the filter layer has already guaranteed the transition is
 * available — a throw here means the action/trigger map and the filters have
 * drifted out of sync.
 */
export function requireNextState(
  machine: MachineName,
  current: string,
  trigger: string
): string {
  const dest = nextState(machine, current, trigger)
  if (dest === null) {
    throw new Error(
      `Illegal ${machine} transition: no "${trigger}" from "${current}". ` +
        `Check protocolActions mapping vs. data/json/protocol_states.json.`
    )
  }
  return dest
}

/** True if `machine` permits `trigger` from `current`. */
export function isLegalTransition(
  machine: MachineName,
  current: string,
  trigger: string
): boolean {
  return TRANSITION_INDEX[machine].get(current)?.has(trigger) ?? false
}

/** Every trigger legal from `current` (deduped, in first-seen order). */
export function legalTriggers(machine: MachineName, current: string): string[] {
  const byTrigger = TRANSITION_INDEX[machine].get(current)
  return byTrigger ? Array.from(byTrigger.keys()) : []
}
