#!/usr/bin/env python

#  Copyright (c) 2026 Carnegie Mellon University and Contributors.
#  - see Contributors.md for a full list of Contributors
#  - see ContributionInstructions.md for information on how you can Contribute to this project
#  Vultron Multiparty Coordinated Vulnerability Disclosure Protocol Prototype is
#  licensed under a MIT (SEI)-style license, please see LICENSE.md distributed
#  with this Software or contact permission@sei.cmu.edu for full terms.
#  Created, in part, with funding and support from the United States Government
#  (see Acknowledgments file). This program may include and/or can make use of
#  certain third party source code, object code, documentation and other files
#  ("Third Party Software"). See LICENSE.md for more details.
#  Carnegie Mellon®, CERT® and CERT Coordination Center® are registered in the
#  U.S. Patent and Trademark Office by Carnegie Mellon University

"""Export Vultron protocol state machines to a JSON artifact for downstream
consumers (e.g. the ``ui/`` visualization demos).

The demos must not hardcode their own copy of "which states and transitions
the protocol allows". Instead they read the JSON this script produces, so the
demo automatically tracks any change to the authoritative state machines in
:mod:`vultron.core.states`.

The four authoritative machines are read uniformly through their public
``create_*_machine()`` factories (the same surface :func:`mermaid_machine`
uses), so this script never needs to know how each enum serializes:

- **RM**  — Report Management (per-participant)
- **EM**  — Embargo Management (case-level)
- **VFD** — Vendor Fix Development (per-participant; the ``vfd``→``VFD`` ladder)
- **PXA** — Public / eXploit / Attacks (case-level)

Output is written to ``data/json/protocol_states.json`` at the repository root
(following the SSVC ``data/json/`` precedent). The output is **deterministic**
— no timestamps, stable ordering — so a CI drift test can assert the committed
file matches a fresh export.

Usage::

    uv run export-demo-states

Run it once now, commit the generated JSON, and re-run it (then re-commit)
whenever the protocol's state machines change. The drift test
``test/test_demo_states_export.py`` fails CI if the committed file goes stale.
"""

import json
from enum import Enum
from pathlib import Path
from typing import Any

from transitions import Machine

from vultron.core.states.cs import create_pxa_machine, create_vfd_machine
from vultron.core.states.em import create_em_machine
from vultron.core.states.rm import create_rm_machine

# Where the artifact lives, relative to the repo root.
# __file__ = <repo>/vultron/scripts/export_states.py
#   parents[0] = scripts, parents[1] = vultron, parents[2] = <repo root>
REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = REPO_ROOT / "data" / "json" / "protocol_states.json"

# Fixed, ordered list of machines so the exported JSON is deterministic.
_MACHINES = (
    ("rm", create_rm_machine),
    ("em", create_em_machine),
    ("vfd", create_vfd_machine),
    ("pxa", create_pxa_machine),
)


def _state_name(value: object) -> str:
    """Normalize a pytransitions state reference to its bare token.

    pytransitions identifies enum-backed states by their enum ``.name``
    (e.g. ``START``, ``vfd``). Accept an enum member or a string and return
    the clean token the demos use.
    """
    if isinstance(value, Enum):
        return value.name
    text = str(value)
    # Defensive: strip any "ClassName.member" prefix should one ever appear.
    return text.rsplit(".", 1)[-1] if "." in text else text


def _machine_to_dict(machine: Machine) -> dict[str, Any]:
    """Serialize a single state machine to ``{initial, states, transitions}``."""
    states = [_state_name(s) for s in machine.states]

    transitions: list[dict[str, str]] = []
    for trigger_name in machine.events.keys():
        for trans in machine.get_transitions(trigger=trigger_name):
            transitions.append(
                {
                    "trigger": str(trigger_name),
                    "source": _state_name(trans.source),
                    "dest": _state_name(trans.dest),
                }
            )

    return {
        "initial": _state_name(machine.initial),
        "states": states,
        "transitions": transitions,
    }


def build_payload() -> dict[str, Any]:
    """Build the full, deterministic export payload.

    Importable by the drift test so it can compare against the committed file
    without touching the filesystem.
    """
    payload: dict[str, Any] = {
        "_README": (
            "Generated by `uv run export-demo-states` "
            "(vultron/scripts/export_states.py). Do not edit by hand; "
            "re-run the exporter and commit the result instead."
        )
    }
    for key, factory in _MACHINES:
        payload[key] = _machine_to_dict(factory())
    return payload


def _serialize(payload: dict[str, Any]) -> str:
    """Render the payload as the canonical on-disk string (stable + newline)."""
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    """Write the export to ``data/json/protocol_states.json``."""
    payload = build_payload()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_serialize(payload), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
