"""README generator for monthly history directories.

Scans ``plan/history/YYMM/`` for entry files, reads their YAML frontmatter,
and writes a summary table to ``plan/history/YYMM/README.md``.

See ``specs/history-management.yaml`` HM-01-003, HM-02-004, HM-03-006,
HM-06-006.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from pathlib import Path

import frontmatter
from pydantic import ValidationError

from vultron.metadata.history.models import HistoryEntryFrontmatter


@dataclass
class _EntryMeta:
    """Parsed frontmatter from a single history entry file."""

    title: str = ""
    entry_type: str = ""
    timestamp: datetime.datetime = field(
        default_factory=lambda: datetime.datetime(
            1970, 1, 1, tzinfo=datetime.timezone.utc
        )
    )
    source: str = ""
    path: Path = field(default_factory=Path)


def _parse_entry(path: Path) -> _EntryMeta:
    """Read and validate YAML frontmatter from a history entry file.

    Raises:
        ValueError: If the frontmatter is malformed, missing, or fails
            required-field validation (HM-02-001, HM-06-002).
    """
    try:
        post = frontmatter.load(str(path))
    except Exception as exc:  # noqa: BLE001
        raise ValueError(f"{path}: malformed YAML frontmatter: {exc}") from exc

    if not post.metadata:
        raise ValueError(
            f"{path}: missing frontmatter block — entry must begin with a "
            "YAML frontmatter block containing title, type, timestamp, and source"
        )

    try:
        meta = HistoryEntryFrontmatter.model_validate(post.metadata)
    except ValidationError as exc:
        missing = [e["loc"][0] for e in exc.errors() if e["loc"]]
        fields = ", ".join(str(f) for f in missing) if missing else str(exc)
        raise ValueError(
            f"{path}: invalid history frontmatter: missing or invalid "
            f"field(s): {fields}"
        ) from exc

    # timestamp is required on HistoryEntryFrontmatter (HM-06-002).
    return _EntryMeta(
        title=meta.title,
        entry_type=meta.type.value,
        timestamp=meta.timestamp,
        source=meta.source,
        path=path,
    )


def _month_label(yymm: str) -> str:
    """Convert ``YYMM`` to a human-readable label, e.g. ``2604`` → ``April 2026``."""
    try:
        dt = datetime.datetime.strptime(yymm, "%y%m")
        return dt.strftime("%B %Y")
    except ValueError:
        return yymm


def regenerate_readme(month_dir: Path) -> Path:
    """Scan *month_dir* for entry files and write a summary README.

    Args:
        month_dir: Path to ``plan/history/YYMM/``.

    Returns:
        Path to the written ``README.md`` file.
    """
    readme_path = month_dir / "README.md"
    entries: list[_EntryMeta] = []

    for md_file in sorted(month_dir.rglob("*.md")):
        if md_file.name == "README.md":
            continue
        meta = _parse_entry(md_file)
        entries.append(meta)

    # Sort by timestamp descending (HM-06-006).
    entries.sort(key=lambda e: e.timestamp, reverse=True)

    label = _month_label(month_dir.name)
    lines: list[str] = [
        f"# History: {label}",
        "",
        "<!-- Auto-generated by `append-history`. Do not edit manually. -->",
        "",
        "| Date | Time (UTC) | Type | Source | Title |",
        "|------|------------|------|--------|-------|",
    ]
    for entry in entries:

        def _cell(value: str) -> str:
            return value.replace("\n", " ").replace("|", "\\|")

        date_str = entry.timestamp.strftime("%Y-%m-%d")
        time_str = entry.timestamp.strftime("%H:%M")
        lines.append(
            f"| {_cell(date_str)} | {_cell(time_str)}"
            f" | {_cell(entry.entry_type)}"
            f" | {_cell(entry.source)} | {_cell(entry.title)} |"
        )

    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return readme_path
