"""README generator for monthly history directories.

Scans ``plan/history/YYMM/`` for entry files, reads their YAML frontmatter,
and writes a summary table to ``plan/history/YYMM/README.md``.

See ``specs/history-management.yaml`` HM-01-003, HM-02-004, HM-03-006.
"""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from pathlib import Path

import frontmatter


@dataclass
class _EntryMeta:
    """Parsed frontmatter from a single history entry file."""

    title: str = ""
    entry_type: str = ""
    date: str = ""
    source: str = ""
    path: Path = field(default_factory=Path)


def _parse_entry(path: Path) -> _EntryMeta:
    """Read YAML frontmatter from a history entry file."""
    try:
        post = frontmatter.load(str(path))
    except Exception:  # noqa: BLE001  # malformed frontmatter → skip
        return _EntryMeta(path=path)

    return _EntryMeta(
        title=str(post.metadata.get("title", "")),
        entry_type=str(post.metadata.get("type", "")),
        date=str(post.metadata.get("date", "")),
        source=str(post.metadata.get("source", "")),
        path=path,
    )


def _month_label(yymm: str) -> str:
    """Convert ``YYMM`` to a human-readable label, e.g. ``2604`` → ``April 2026``."""
    try:
        dt = datetime.datetime.strptime(yymm, "%y%m")
        return dt.strftime("%B %Y")
    except ValueError:
        return yymm


def regenerate_readme(month_dir: Path) -> Path:
    """Scan *month_dir* for entry files and write a summary README.

    Args:
        month_dir: Path to ``plan/history/YYMM/``.

    Returns:
        Path to the written ``README.md`` file.
    """
    readme_path = month_dir / "README.md"
    entries: list[_EntryMeta] = []

    for md_file in sorted(month_dir.rglob("*.md")):
        if md_file.name == "README.md":
            continue
        meta = _parse_entry(md_file)
        if meta.title or meta.source:
            entries.append(meta)

    # Sort by date descending, then type ascending for stable ordering.
    entries.sort(key=lambda e: (e.date, e.entry_type), reverse=True)

    label = _month_label(month_dir.name)
    lines: list[str] = [
        f"# History: {label}",
        "",
        "<!-- Auto-generated by `append-history`. Do not edit manually. -->",
        "",
        "| Date | Type | Source | Title |",
        "|------|------|--------|-------|",
    ]
    for entry in entries:
        # Sanitize cell values: escape pipe chars and strip newlines so the
        # Markdown table renders correctly regardless of frontmatter content.
        def _cell(value: str) -> str:
            return value.replace("\n", " ").replace("|", "\\|")

        lines.append(
            f"| {_cell(entry.date)} | {_cell(entry.entry_type)}"
            f" | {_cell(entry.source)} | {_cell(entry.title)} |"
        )

    readme_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return readme_path
