"""
Backward-compatibility shim. All content has moved to vultron.wire.as2.extractor.
"""

# Re-export everything from the canonical location so existing imports continue to work.
from vultron.wire.as2.extractor import (  # noqa: F401
    ActivityPattern,
    CreateEmbargoEvent,
    AddEmbargoEventToCase,
    RemoveEmbargoEventFromCase,
    AnnounceEmbargoEventToCase,
    InviteToEmbargoOnCase,
    AcceptInviteToEmbargoOnCase,
    RejectInviteToEmbargoOnCase,
    CreateReport,
    ReportSubmission,
    AckReport,
    ValidateReport,
    InvalidateReport,
    CloseReport,
    CreateCase,
    UpdateCase,
    EngageCase,
    DeferCase,
    AddReportToCase,
    SuggestActorToCase,
    AcceptSuggestActorToCase,
    RejectSuggestActorToCase,
    OfferCaseOwnershipTransfer,
    AcceptCaseOwnershipTransfer,
    RejectCaseOwnershipTransfer,
    InviteActorToCase,
    AcceptInviteActorToCase,
    RejectInviteActorToCase,
    CloseCase,
    CreateNote,
    AddNoteToCase,
    RemoveNoteFromCase,
    CreateCaseParticipant,
    AddCaseParticipantToCase,
    RemoveCaseParticipantFromCase,
    CreateCaseStatus,
    AddCaseStatusToCase,
    CreateParticipantStatus,
    AddParticipantStatusToParticipant,
)
