#!/usr/bin/env python
"""file: zerodays
author: adh
created_at: 3/16/23 1:37 PM
"""
#  Copyright (c) 2023. Carnegie Mellon University
#
#  See LICENSE for details

from enum import IntEnum, auto


class ZeroDayType(IntEnum):
    """Enum for the type of Zero Day"""

    NOT_APPLICABLE = auto()

    ZERO_DAY_VULNERABILITY_TYPE_1 = auto()
    ZERO_DAY_VULNERABILITY_TYPE_2 = auto()
    ZERO_DAY_VULNERABILITY_TYPE_3 = auto()
    ZERO_DAY_EXPLOIT_TYPE_1 = auto()
    ZERO_DAY_EXPLOIT_TYPE_2 = auto()
    ZERO_DAY_EXPLOIT_TYPE_3 = auto()
    ZERO_DAY_ATTACK_TYPE_1 = auto()
    ZERO_DAY_ATTACK_TYPE_2 = auto()
    ZERO_DAY_ATTACK_TYPE_3 = auto()

    # convenience aliases
    NA = NOT_APPLICABLE
    VULNERABILITY_TYPE_1 = ZERO_DAY_VULNERABILITY_TYPE_1
    VULNERABILITY_TYPE_2 = ZERO_DAY_VULNERABILITY_TYPE_2
    VULNERABILITY_TYPE_3 = ZERO_DAY_VULNERABILITY_TYPE_3
    EXPLOIT_TYPE_1 = ZERO_DAY_EXPLOIT_TYPE_1
    EXPLOIT_TYPE_2 = ZERO_DAY_EXPLOIT_TYPE_2
    EXPLOIT_TYPE_3 = ZERO_DAY_EXPLOIT_TYPE_3
    ATTACK_TYPE_1 = ZERO_DAY_ATTACK_TYPE_1
    ATTACK_TYPE_2 = ZERO_DAY_ATTACK_TYPE_2
    ATTACK_TYPE_3 = ZERO_DAY_ATTACK_TYPE_3

    ZD_NA = NOT_APPLICABLE
    ZD_VUL_1 = ZERO_DAY_VULNERABILITY_TYPE_1
    ZD_VUL_2 = ZERO_DAY_VULNERABILITY_TYPE_2
    ZD_VUL_3 = ZERO_DAY_VULNERABILITY_TYPE_3
    ZD_EXP_1 = ZERO_DAY_EXPLOIT_TYPE_1
    ZD_EXP_2 = ZERO_DAY_EXPLOIT_TYPE_2
    ZD_EXP_3 = ZERO_DAY_EXPLOIT_TYPE_3
    ZD_ATK_1 = ZERO_DAY_ATTACK_TYPE_1
    ZD_ATK_2 = ZERO_DAY_ATTACK_TYPE_2
    ZD_ATK_3 = ZERO_DAY_ATTACK_TYPE_3
