name: "Lint Markdown"

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.md"
      - .github/workflows/lint_md_all.yml
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.md"
      - .github/workflows/lint_md_all.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23.1.0
      with:
        globs: "**/*.md"
        config: .markdownlint-cli2.yaml
