on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: build
        run: |
          mkdocs build --verbose
          ls -lR site

      - name: deploy
        run: |
          echo "do deploy here"