# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - vultron/**
      - test/**
      - pyproject.toml
      - .github/workflows/python-app.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - vultron/**
      - test/**
      - pyproject.toml
      - .github/workflows/python-app.yml

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-tags: true
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv 
        uv sync --dev --frozen
    - uses: psf/black@c6755bb741b6481d6b3d3bb563c83fa060db96c9 # 26.3.1
    - name: Test with pytest
      run: |
        uv run pytest
    - name: Build
      run: |
        uv build
    - name: Upload Artifacts
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: vultron
        path: dist/vultron-*.tar.gz
        retention-days: 14
